### PR TITLE
Added example-app

### PR DESCRIPTION
**Pull request by auser**
Added example app and the ability to add options.

Currently the only option available is `python`, but it's extensible.

Also if no options or `python` isn't passed, it uses `zx.which()` command to find `python`

### CODE REVIEW

**Comment by ConProgramming** [comment]
Amazing to have the `python` option! Super nice to have the configurability of options.

My thoughts are 
- Name the external option `python_path`, like you put internally, just for sure clarity
- I try to keep the example in the separate repo, https://github.com/semicognitive/sveltekit-modal-langchain, any thoughts on pros of in the same repo vs separate?
- Make the default path be `python3` instead of `python` - or else this is a breaking change

**Comment by auser** [comment]
I agree that the option name should be `python_path` and happy to move back to `python3`

I like having an example in the repo for getting started. I left it really bare so it wasn't complex or anything. My preference is to have a really basic version and maybe links to the example in the README.

Pushed an update

**Comment by ConProgramming** [comment]
Okay, fine with the example in the repo if that's preffered for some
Push the `python3` change and I'm happy to merge 😃

**Comment by auser** [comment]
Updated this to use `python3`

**Comment by ConProgramming** [comment]
Merged, thank you!

**Pull request merged**
